### ISSUE TITLE
Concept embedding rescaling

### ISSUE THREAD

**Issue by VanyaBK** [snap-research/MyVLM#3]
Hi, thank you for your wonderful work! I have a doubt regarding the rescaling of concept embeddings, I am not sure if I missed it, but I could not find it in the code. How exactly is the concept embedding concatenated with the embeddings from the projection layer of Llava when the sizes are vastly different, do you add another projection layer to project the concept embedding to the size of the embedding obtained from the projection layer of Llava?

**Comment by yuval-alaluf** [comment]
The concept embeddings and the image features are the same dimension so concatenating them is straightforward. In all of our models, the concatenation happens in the `MyVLMLayer` class:
https://github.com/snap-research/MyVLM/blob/d4893f5274bb07db370c88e6c4bed9b4b95a28c1/myvlm/myvlm_layer.py#L168-L169
Notice that we define the dimension of the concept embedding to match the dimension of the image features in advance so that concatenating them is possible: 
https://github.com/snap-research/MyVLM/blob/d4893f5274bb07db370c88e6c4bed9b4b95a28c1/myvlm/myvlm.py#L38-L42
For each VLM, we just need to know the dimension ahead of time when defining the layer. 
I hope this helps!

**Comment by VanyaBK** [comment]
But the concept embedding obtained as face embedding has a fixed dimension dependent on the face recognition model like arcface. So how exactly is it rescaled to match the dimensions of the image features?

**Comment by yuval-alaluf** [comment]
This could be a bit confusing. The concept embedding is not taken from the face recognition model. The face recognition model is only used as a classifier to determine if a specific concept is present in the image or not. Once that concept is identified, we use it's concept embedding which resides in the output space of the VLM. These are two different embedding spaces. Hope this helps clarify this.

**Comment by VanyaBK** [comment]
So what is the use of classifying if the concept is a face or not, if the embedding is eventually obtained from the concept embedding space?

**Comment by yuval-alaluf** [comment]
We need the classification step because assume that you have taught the model 10 different people and now you get a new image. You want to be able to understand who that person in the image is so that you can personalize the results specifically with respect to that person. Once you know that the person is e.g., "Bob", you can pass Bob's previously-learned concept embedding to the VLM rather than "John's" concept embedding, which would give you the incorrect personalized caption.

**Comment by VanyaBK** [comment]
My understanding was that even for objects similar concept embeddings are used, which is why I was confused why the classifier is necessary. Are the concept embeddings not relevant for objects?

**Comment by yuval-alaluf** [comment]
The concept embedding is relevant for both people and objects. 
The only reason we need the classifier is for inference. When we get a new image we want to identify what concept is in the image - is it Bob, John, is it my pet dog? Once we know what concept is in the image, we can fetch the concept's learned embedding and concatenate it to the VLM vision encoder's image features.
